name: "CI"

on:
  pull_request: # Triggered on pull requests to any branch
  push:
    branches: # Additionally, trigger on push events to specific branches
      - master

jobs:
  backend-build:
    runs-on: ubuntu-latest
    name: Quarkus build test
    defaults:
      run:
        working-directory: 'backend'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn quarkus:build package
